import type { ActiveStatus } from '@/components/ui/StatusBadge'
import type { TranslationKey } from '@/lib/i18n'

export type ClassStatus = ActiveStatus

export interface SchoolClass {
  id: string
  name: string
  description: string
  /** ISO dates (YYYY-MM-DD) of the first and last day of the class. */
  startDate: string
  endDate: string
  status: ClassStatus
  /** Students enter this code to join the class; generated by the system. */
  code: string
}

// The code is not entered by hand.
export type ClassInput = Omit<SchoolClass, 'id' | 'code'>

export type ClassFormErrors = Partial<Record<keyof ClassInput, TranslationKey>>
